<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //  currency settings

        DB::insert("INSERT INTO `currency` (`id`, `country`, `currency`, `code`, `symbol`, `currency_status`, `status`, `created_at`, `updated_at`) VALUES
                (1, 'Albania', 'Leke', 'ALL', 'Lek', 0, 1, NULL, NULL),
                (2, 'America', 'Dollars', 'USD', '$', 1, 1, NULL, NULL),
                (3, 'Afghanistan', 'Afghanis', 'AFN', 'AFN', 0, 1, NULL, NULL),
                (4, 'Argentina', 'Pesos', 'ARS', '$', 0, 1, NULL, NULL),
                (5, 'Aruba', 'Guilders', 'AWG', 'ƒ', 0, 1, NULL, NULL),
                (6, 'Australia', 'Dollars', 'AUD', '$', 0, 1, NULL, NULL),
                (7, 'Azerbaijan', 'New Manats', 'AZN', 'ман', 0, 1, NULL, NULL),
                (8, 'Bahamas', 'Dollars', 'BSD', '$', 0, 1, NULL, NULL),
                (9, 'Barbados', 'Dollars', 'BBD', '$', 0, 1, NULL, NULL),
                (10, 'Belarus', 'Rubles', 'BYR', 'p.', 0, 1, NULL, NULL),
                (11, 'Belgium', 'Euro', 'EUR', '€', 0, 1, NULL, NULL),
                (12, 'Beliz', 'Dollars', 'BZD', 'BZ$', 0, 1, NULL, NULL),
                (13, 'Bermuda', 'Dollars', 'BMD', '$', 0, 1, NULL, NULL),
                (14, 'Bolivia', 'Bolivianos', 'BOB', 'b', 0, 1, NULL, NULL),
                (15, 'Bosnia and Herzegovina', 'Convertible Marka', 'BAM', 'KM', 0, 1, NULL, NULL),
                (16, 'Botswana', 'Pula', 'BWP', 'P', 0, 1, NULL, NULL),
                (17, 'Bulgaria', 'Leva', 'BGN', 'лв', 0, 1, NULL, NULL),
                (18, 'Brazil', 'Reais', 'BRL', 'R$', 0, 1, NULL, NULL),
                (19, 'Britain (United Kingdom)', 'Pounds', 'GBP', '£', 0, 1, NULL, NULL),
                (20, 'Brunei Darussalam', 'Dollars', 'BND', '$', 0, 1, NULL, NULL),
                (21, 'Cambodia', 'Riels', 'KHR', '៛', 0, 1, NULL, NULL),
                (22, 'Canada', 'Dollars', 'CAD', '$', 0, 1, NULL, NULL),
                (23, 'Cayman Islands', 'Dollars', 'KYD', '$', 0, 1, NULL, NULL),
                (24, 'Chile', 'Pesos', 'CLP', '$', 0, 1, NULL, NULL),
                (25, 'China', 'Yuan Renminbi', 'CNY', '¥', 0, 1, NULL, NULL),
                (26, 'Colombia', 'Pesos', 'COP', '$', 0, 1, NULL, NULL),
                (27, 'Costa Rica', 'Colón', 'CRC', '₡', 0, 1, NULL, NULL),
                (28, 'Croatia', 'Kuna', 'HRK', 'kn', 0, 1, NULL, NULL),
                (29, 'Cuba', 'Pesos', 'CUP', '₱', 0, 1, NULL, NULL),
                (30, 'Cyprus', 'Euro', 'EUR', '€', 0, 1, NULL, '2020-05-12 05:19:27'),
                (31, 'Czech Republic', 'Koruny', 'CZK', 'Kč', 0, 1, NULL, NULL),
                (32, 'Denmark', 'Kroner', 'DKK', 'kr', 0, 1, NULL, NULL),
                (33, 'Dominican Republic', 'Pesos', 'DOP ', 'RD$', 0, 1, NULL, NULL),
                (34, 'East Caribbean', 'Dollars', 'XCD', '$', 0, 1, NULL, NULL),
                (35, 'Egypt', 'Pounds', 'EGP', '£', 0, 1, NULL, NULL),
                (36, 'El Salvador', 'Colones', 'SVC', '$', 0, 1, NULL, NULL),
                (37, 'England (United Kingdom)', 'Pounds', 'GBP', '£', 0, 1, NULL, NULL),
                (38, 'Euro', 'Euro', 'EUR', '€', 0, 1, NULL, NULL),
                (39, 'Falkland Islands', 'Pounds', 'FKP', '£', 0, 1, NULL, NULL),
                (40, 'Fiji', 'Dollars', 'FJD', '$', 0, 1, NULL, NULL),
                (41, 'France', 'Euro', 'EUR', '€', 0, 1, NULL, NULL),
                (42, 'Ghana', 'Cedis', 'GHS', '¢', 0, 1, NULL, NULL),
                (43, 'Gibraltar', 'Pounds', 'GIP', '£', 0, 1, NULL, NULL),
                (44, 'Greece', 'Euro', 'EUR', '€', 0, 1, NULL, NULL),
                (45, 'Guatemala', 'Quetzales', 'GTQ', 'Q', 0, 1, NULL, NULL),
                (46, 'Guernsey', 'Pounds', 'GGP', '£', 0, 1, NULL, NULL),
                (47, 'Guyana', 'Dollars', 'GYD', '$', 0, 1, NULL, NULL),
                (48, 'Holland (Netherlands)', 'Euro', 'EUR', '€', 0, 1, NULL, NULL),
                (49, 'Honduras', 'Lempiras', 'HNL', 'L', 0, 1, NULL, NULL),
                (50, 'Hong Kong', 'Dollars', 'HKD', '$', 0, 1, NULL, NULL),
                (51, 'Hungary', 'Forint', 'HUF', 'Ft', 0, 1, NULL, NULL),
                (52, 'Iceland', 'Kronur', 'ISK', 'kr', 0, 1, NULL, NULL),
                (53, 'India', 'Rupees', 'INR', 'Rp', 0, 1, NULL, NULL),
                (54, 'Indonesia', 'Rupiahs', 'IDR', 'Rp', 0, 1, NULL, NULL),
                (55, 'Iran', 'Rials', 'IRR', '﷼', 0, 1, NULL, NULL),
                (56, 'Ireland', 'Euro', 'EUR', '€', 0, 1, NULL, NULL),
                (57, 'Isle of Man', 'Pounds', 'IMP', '£', 0, 1, NULL, NULL),
                (58, 'Israel', 'New Shekels', 'ILS', '₪', 0, 1, NULL, NULL),
                (59, 'Italy', 'Euro', 'EUR', '€', 0, 1, NULL, NULL),
                (60, 'Jamaica', 'Dollars', 'JMD', 'J$', 0, 1, NULL, NULL),
                (61, 'Japan', 'Yen', 'JPY', '¥', 0, 1, NULL, NULL),
                (62, 'Jersey', 'Pounds', 'JEP', '£', 0, 1, NULL, NULL),
                (63, 'Kazakhstan', 'Tenge', 'KZT', 'лв', 0, 1, NULL, NULL),
                (64, 'Korea (North)', 'Won', 'KPW', '₩', 0, 1, NULL, NULL),
                (65, 'Korea (South)', 'Won', 'KRW', '₩', 0, 1, NULL, NULL),
                (66, 'Kyrgyzstan', 'Soms', 'KGS', 'лв', 0, 1, NULL, NULL),
                (67, 'Laos', 'Kips', 'LAK', '₭', 0, 1, NULL, NULL),
                (68, 'Latvia', 'Lati', 'LVL', 'Ls', 0, 1, NULL, NULL),
                (69, 'Lebanon', 'Pounds', 'LBP', '£', 0, 1, NULL, NULL),
                (70, 'Liberia', 'Dollars', 'LRD', '$', 0, 1, NULL, NULL),
                (71, 'Liechtenstein', 'Switzerland Francs', 'CHF', 'CHF', 0, 1, NULL, NULL),
                (72, 'Lithuania', 'Litai', 'LTL', 'Lt', 0, 1, NULL, NULL),
                (73, 'Luxembourg', 'Euro', 'EUR', '€', 0, 1, NULL, NULL),
                (74, 'Macedonia', 'Denars', 'MKD', 'ден', 0, 1, NULL, NULL),
                (75, 'Malaysia', 'Ringgits', 'MYR', 'RM', 0, 1, NULL, NULL),
                (76, 'Malta', 'Euro', 'EUR', '€', 0, 1, NULL, NULL),
                (77, 'Mauritius', 'Rupees', 'MUR', '₨', 0, 1, NULL, NULL),
                (78, 'Mexico', 'Pesos', 'MXN', '$', 0, 1, NULL, NULL),
                (79, 'Mongolia', 'Tugriks', 'MNT', '₮', 0, 1, NULL, NULL),
                (80, 'Mozambique', 'Meticais', 'MZN', 'MT', 0, 1, NULL, NULL),
                (81, 'Namibia', 'Dollars', 'NAD', '$', 0, 1, NULL, NULL),
                (82, 'Nepal', 'Rupees', 'NPR', '₨', 0, 1, NULL, NULL),
                (83, 'Netherlands Antilles', 'Guilders', 'ANG', 'ƒ', 0, 1, NULL, NULL),
                (84, 'Netherlands', 'Euro', 'EUR', '€', 0, 1, NULL, NULL),
                (85, 'New Zealand', 'Dollars', 'NZD', '$', 0, 1, NULL, NULL),
                (86, 'Nicaragua', 'Cordobas', 'NIO', 'C$', 0, 1, NULL, NULL),
                (87, 'Nigeria', 'Nairas', 'NGN', '₦', 0, 1, NULL, NULL),
                (88, 'North Korea', 'Won', 'KPW', '₩', 0, 1, NULL, NULL),
                (89, 'Norway', 'Krone', 'NOK', 'kr', 0, 1, NULL, NULL),
                (90, 'Oman', 'Rials', 'OMR', '﷼', 0, 1, NULL, NULL),
                (91, 'Pakistan', 'Rupees', 'PKR', '₨', 0, 1, NULL, NULL),
                (92, 'Panama', 'Balboa', 'PAB', 'B/.', 0, 1, NULL, NULL),
                (93, 'Paraguay', 'Guarani', 'PYG', 'Gs', 0, 1, NULL, NULL),
                (94, 'Peru', 'Nuevos Soles', 'PEN', 'S/.', 0, 1, NULL, NULL),
                (95, 'Philippines', 'Pesos', 'PHP', 'Php', 0, 1, NULL, NULL),
                (96, 'Poland', 'Zlotych', 'PLN', 'zł', 0, 1, NULL, NULL),
                (97, 'Qatar', 'Rials', 'QAR', '﷼', 0, 1, NULL, NULL),
                (98, 'Romania', 'New Lei', 'RON', 'lei', 0, 1, NULL, NULL),
                (99, 'Russia', 'Rubles', 'RUB', 'руб', 0, 1, NULL, NULL),
                (100, 'Saint Helena', 'Pounds', 'SHP', '£', 0, 1, NULL, NULL),
                (101, 'Saudi Arabia', 'Riyals', 'SAR', '﷼', 0, 1, NULL, NULL),
                (102, 'Serbia', 'Dinars', 'RSD', 'Дин.', 0, 1, NULL, NULL),
                (103, 'Seychelles', 'Rupees', 'SCR', '₨', 0, 1, NULL, NULL),
                (104, 'Singapore', 'Dollars', 'SGD', '$', 0, 1, NULL, NULL),
                (105, 'Slovenia', 'Euro', 'EUR', '€', 0, 1, NULL, NULL),
                (106, 'Solomon Islands', 'Dollars', 'SBD', '$', 0, 1, NULL, NULL),
                (107, 'Somalia', 'Shillings', 'SOS', 'S', 0, 1, NULL, NULL),
                (108, 'South Africa', 'Rand', 'ZAR', 'R', 0, 1, NULL, NULL),
                (109, 'South Korea', 'Won', 'KRW', '₩', 0, 1, NULL, NULL),
                (110, 'Spain', 'Euro', 'EUR', '€', 0, 1, NULL, '2020-02-09 00:13:59'),
                (111, 'Sri Lanka', 'Rupees', 'LKR', '₨', 0, 1, NULL, '2020-02-03 02:18:58'),
                (112, 'Sweden', 'Kronor', 'SEK', 'kr', 0, 1, NULL, NULL),
                (113, 'Switzerland', 'Francs', 'CHF', 'CHF', 0, 1, NULL, '2020-02-03 04:35:58'),
                (114, 'Suriname', 'Dollars', 'SRD', '$', 0, 1, NULL, NULL),
                (115, 'Syria', 'Pounds', 'SYP', '£', 0, 1, NULL, NULL),
                (116, 'Taiwan', 'New Dollars', 'TWD', 'NT$', 0, 1, NULL, NULL),
                (117, 'Thailand', 'Baht', 'THB', '฿', 0, 1, NULL, NULL),
                (118, 'Trinidad and Tobago', 'Dollars', 'TTD', 'TT$', 0, 1, NULL, NULL),
                (119, 'Turkey', 'Lira', 'TRY', 'TL', 0, 1, NULL, NULL),
                (120, 'Turkey', 'Liras', 'TRL', '£', 0, 1, NULL, NULL),
                (121, 'Tuvalu', 'Dollars', 'TVD', '$', 0, 1, NULL, NULL),
                (122, 'Ukraine', 'Hryvnia', 'UAH', '₴', 0, 1, NULL, NULL),
                (123, 'United Kingdom', 'Pounds', 'GBP', '£', 0, 1, NULL, NULL),
                (124, 'United States of America', 'Dollars', 'USD', '$', 1, 1, NULL, '2020-05-12 15:55:30'),
                (125, 'Uruguay', 'Pesos', 'UYU', 'u', 0, 1, NULL, '2020-02-03 01:20:55'),
                (126, 'Uzbekistan', 'Sums', 'UZS', 'лв', 0, 1, NULL, NULL),
                (127, 'Vatican City', 'Euro', 'EUR', '€', 0, 1, NULL, '2020-02-03 23:44:40'),
                (128, 'Venezuela', 'Bolivares Fuertes', 'VEF', 'Bs', 0, 1, NULL, '2020-02-03 02:18:46'),
                (129, 'Vietnam', 'Dong', 'VND', '₫', 0, 1, NULL, '2020-02-09 00:14:06'),
                (130, 'Yemen', 'Rials', 'YER', '﷼', 0, 1, NULL, NULL),
                (131, 'Zimbabwe', 'Zimbabwe Dollars', 'ZWD', 'Z$', 0, 1, NULL, '2020-02-03 01:20:40'),
                (133, 'Bangladesh', 'bangladeshi taka', 'BDT', '৳', 0, 1, '2020-02-03 00:38:33', '2020-05-12 15:55:30')");
    }
}
